In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X= df.drop('sales',axis=1)

In [5]:
y= df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [8]:
poly_features=polynomial_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
X_train.shape

(140, 19)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler()

In [16]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [17]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [18]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [19]:
from sklearn.linear_model import Ridge

In [20]:
ridge_model = Ridge(alpha=10)

In [21]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [22]:
test_predictions = ridge_model.predict(X_test)

In [23]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [24]:
MAE = mean_absolute_error(y_test,test_predictions)

In [25]:
MAE

0.5774404204714183

In [26]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))
RMSE

0.8946386461319685

In [27]:
from sklearn.linear_model import RidgeCV

In [28]:
ridge_cv_model = RidgeCV(alphas=([0.1,1.,10.0]),scoring= 'neg_mean_absolute_error')

In [29]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=[0.1, 1.0, 10.0], scoring='neg_mean_absolute_error')

In [30]:
ridge_cv_model.alpha_

0.1

In [31]:
from sklearn.metrics import SCORERS

In [32]:
test_predictions = ridge_cv_model.predict(X_test)

In [33]:
MAE = mean_absolute_error(y_test,test_predictions)
MAE


0.42737748843373746

In [34]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))
RMSE

0.6180719926921404

In [35]:
from sklearn.linear_model import LassoCV

In [52]:
lasso_cv_model = LassoCV(eps=0.001,max_iter=100000)

In [53]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(max_iter=100000)

In [54]:
lasso_cv_model.alpha_

0.004943070909225827

In [55]:
test_predictions = lasso_cv_model.predict(X_test)

In [56]:
MAE = mean_absolute_error(y_test,test_predictions)

In [57]:
MAE

0.43350346185900673

In [58]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))
RMSE

0.6063140748984039

In [59]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [60]:
from sklearn.linear_model import ElasticNetCV

In [63]:
elastic_model= ElasticNetCV(l1_ratio = [.1, .5, .7,
    .9, .95, .99, 1],eps=0.001,n_alphas=100,max_iter=1000000)

In [64]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [66]:
elastic_model.alpha_

0.004943070909225827

In [67]:
test_predictions=elastic_model.predict(X_test)

In [68]:
MAE = mean_absolute_error(y_test,test_predictions)

In [69]:
MAE

0.43350346185900673

In [70]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))
RMSE

0.6063140748984039

In [71]:
from joblib import dump,load

In [73]:
dump(elastic_model,'final_reguralization_model.joblib')

['final_reguralization_model.joblib']

In [74]:
loaded_model = load('final_reguralization_model.joblib')

In [75]:
loaded_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

ValueError: X has 3 features, but ElasticNetCV is expecting 19 features as input.